[versions]
agp = "8.11.2"
kotlin = "2.1.10"

# Octopus
octopusSdk = "1.6.2"

# AndroidX
coreKtx = "1.16.0"
activityKtx = "1.10.1"

# Compose
composeBom = "2025.10.00"

# Activity Compose
activityCompose = "1.10.1"

# Navigation Compose
navigationCompose = "2.9.1"

# Serialization
kotlinxSerialization = "1.9.0"

# DataStore
datastore = "1.1.7"

# Coil
coil = "3.3.0"

[libraries]
# Octopus
octopus-sdk = { group = "com.octopuscommunity", name = "octopus-sdk", version.ref = "octopusSdk" }
octopus-sdk-ui = { group = "com.octopuscommunity", name = "octopus-sdk-ui", version.ref = "octopusSdk" }

# AndroidX
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-activity-ktx = { group = "androidx.activity", name = "activity-ktx", version.ref = "activityKtx" }

# Compose
compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }

# Activity Compose
activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }

# Navigation Compose
navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "navigationCompose" }

# Material3
androidx-material3 = { group = "androidx.compose.material3", name = "material3" }

# Icons
androidx-material-icons-extended = { group = "androidx.compose.material", name = "material-icons-extended" }

# Serialization
kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinxSerialization" }

# DataStore
androidx-datastore = { group = "androidx.datastore", name = "datastore", version.ref = "datastore" }

# Coil
coil-network = { group = "io.coil-kt.coil3", name = "coil-network-okhttp", version.ref = "coil" }
coil-compose = { group = "io.coil-kt.coil3", name = "coil-compose", version.ref = "coil" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }

# Compose
compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }

# Serialization
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }